web:
    image: nginx:latest
    ports:
        - '8080:80'
    volumes:
        - './public:/app/public'
        - './nginx.conf:/etc/nginx/conf.d/default.conf'
    links:
        - php

php:
    image: php:7-fpm
    volumes:
        - './src:/app/src'
