---

version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - './public:/app/public'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - fhws-ical-network

    php:
        image: php:7-fpm
        volumes:
            - './src:/app/src'
        networks:
            - fhws-ical-network

networks:
    fhws-ical-network:
        driver: bridge
