---

version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - '${WEB_IP}:${WEB_PORT}:80'
        volumes:
            - './public:/app/public'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - fhws-ical-network

    php:
        image: php:7-fpm
        volumes:
            - './src:/app/src'
            - './php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
        networks:
            - fhws-ical-network

networks:
    fhws-ical-network:
        driver: bridge

